"""Local retrieval and typed authoritative fact grounding; never execution authority."""

from .adapters import (
    MarketFields,
    ModelInference,
    ModelMetric,
    evidence_from_inference,
    evidence_from_market_fields,
    evidence_from_mcp,
    evidence_from_metric,
    evidence_from_order,
    evidence_from_portfolio,
    evidence_from_quote,
    evidence_from_risk_settings,
)
from .contracts import (
    FactClass,
    FactRequirement,
    GroundingChunk,
    GroundingDecision,
    GroundingDocument,
    GroundingRequest,
    GroundingResult,
    RetrievedEvidence,
    SourceProvenance,
    SourceType,
    ToolEvidence,
)
from .retrieval import (
    GroundingRetriever,
    LocalGroundingIndex,
    build_index,
    chunk_document,
    load_documents,
)
from .service import ALLOWED_FACT_SOURCES, GroundingService, query_index

__all__ = [
    "ALLOWED_FACT_SOURCES",
    "FactClass",
    "FactRequirement",
    "GroundingChunk",
    "GroundingDecision",
    "GroundingDocument",
    "GroundingRequest",
    "GroundingResult",
    "GroundingService",
    "LocalGroundingIndex",
    "RetrievedEvidence",
    "SourceProvenance",
    "SourceType",
    "ToolEvidence",
    "build_index",
    "load_documents",
    "GroundingRetriever",
    "chunk_document",
    "evidence_from_quote",
    "query_index",
    "MarketFields",
    "ModelInference",
    "ModelMetric",
    "evidence_from_inference",
    "evidence_from_market_fields",
    "evidence_from_mcp",
    "evidence_from_metric",
    "evidence_from_order",
    "evidence_from_portfolio",
    "evidence_from_risk_settings",
]
